name: start bot
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: installing packages
      run: npm i
    - name: starting the bot
      run: npm start
