---
name: start bot
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '*/5 * * * *'

env:
  CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
  CONSUMER_KEY_SECRET: ${{ secrets.CONSUMER_KEY_SECRET}}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
  ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
  USERNAME: ${{secrets.USERNAME}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: installing packages
        run: npm i
      - name: starting the bot
        run: npm start
