---
name: start bot
on: push
  #schedule:
   # - cron: '30 * * * *'

env:
  CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
  CONSUMER_KEY_SECRET: ${{ secrets.CONSUMER_KEY_SECRET}}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
  ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
  USERNAME: ${{secrets.USERNAME}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - run: echo ${{ steps.date.outputs.date }}
      - name: Get current date with time
        id: datetime
        run: echo "::set-output name=datetime::$(datetime +'%Y-%m-%d %h:%m:%s')"
      - run: echo ${{ steps.datetime.outputs.datetime }}
      - run: echo $github.event.schedule
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: echo ${CONSUMER_KEY}
      - name: installing packages
        run: npm i
      - name: starting the bot
        run: npm start
